# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Item.create(name: 'Canon i-SENSYS MF3010', price: 248, group: 'printer')
	Item.create(name: 'Canon i-SENSYS MF212w', price: 333, group: 'printer')
	Item.create(name: 'Ricoh SP 111SU', price: 194, group: 'printer')
	Item.create(name: 'Canon i-SENSYS MF211', price: 282, group: 'printer')
	Item.create(name: 'Canon i-SENSYS LBP6030B', price: 168, group: 'printer')
	Item.create(name: 'HP LaserJet Pro P1102 (CE651A)', price: 184, group: 'printer')
	Item.create(name: 'Epson L800', price: 507, group: 'printer')
	Item.create(name: 'Canon PIXMA iP7240', price: 165, group: 'printer')
	Item.create(name: 'Epson L355', price: 396, group: 'printer')
	Item.create(name: 'Samsung SL-M2070', price: 268, group: 'printer')
	Item.create(name: 'Kyocera Mita FS-1040', price: 112, group: 'printer')
	Item.create(name: 'HP LaserJet Pro M125r (CZ176A)', price: 276, group: 'printer')
	Item.create(name: 'Canon PIXMA G2400', price: 338, group: 'printer')
	Item.create(name: 'Canon i-SENSYS MF3010', price: 248, group: 'printer')
	Item.create(name: 'Canon i-SENSYS MF212w', price: 333, group: 'printer')
	Item.create(name: 'Ricoh SP 111SU', price: 194, group: 'printer')
	Item.create(name: 'Canon i-SENSYS MF211', price: 282, group: 'printer')
	Item.create(name: 'Canon i-SENSYS LBP6030B', price: 168, group: 'printer')
	Item.create(name: 'HP LaserJet Pro P1102 (CE651A)', price: 184, group: 'printer')
	Item.create(name: 'Epson L800', price: 507, group: 'printer')
	Item.create(name: 'Canon PIXMA iP7240', price: 165, group: 'printer')
	Item.create(name: 'Epson L355', price: 396, group: 'printer')
	Item.create(name: 'Samsung SL-M2070', price: 268, group: 'printer')
	Item.create(name: 'Kyocera Mita FS-1040', price: 112, group: 'printer')
	Item.create(name: 'HP LaserJet Pro M125r (CZ176A)', price: 276, group: 'printer')
	Item.create(name: 'Canon PIXMA G2400', price: 338, group: 'printer')


	Item.create(name: 'Canon PIXMA G2400', price: 155, group: 'scanner')
	Item.create(name: 'Epson Perfection V370 Photo', price: 260, group: 'scanner')
	Item.create(name: 'Canon CanoScan LiDE 120', price: 128, group: 'scanner')
	Item.create(name: 'HP ScanJet 300', price: 174, group: 'scanner')
	Item.create(name: 'Canon PIXMA G2400', price: 155, group: 'scanner')
	Item.create(name: 'Epson Perfection V370 Photo', price: 260, group: 'scanner')
	Item.create(name: 'Canon CanoScan LiDE 120', price: 128, group: 'scanner')
	Item.create(name: 'HP ScanJet 300', price: 174, group: 'scanner')
	Item.create(name: 'Canon PIXMA G2400', price: 155, group: 'scanner')
	Item.create(name: 'Epson Perfection V370 Photo', price: 260, group: 'scanner')
	Item.create(name: 'Canon CanoScan LiDE 120', price: 128, group: 'scanner')
	Item.create(name: 'HP ScanJet 300', price: 174, group: 'scanner')